// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxMAm3TUZSIpujuR2a9YBS5HVtz-x7Teo',
    appId: '1:1060462154565:web:230916d1e9c932c372242c',
    messagingSenderId: '1060462154565',
    projectId: 'socialnetworkapp-81ecc',
    authDomain: 'socialnetworkapp-81ecc.firebaseapp.com',
    storageBucket: 'socialnetworkapp-81ecc.appspot.com',
    measurementId: 'G-0JVZJLMN8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9hMc300UBBxLT0_jOlckSkP6IOwTsk4',
    appId: '1:1060462154565:android:9da04e731669c92f72242c',
    messagingSenderId: '1060462154565',
    projectId: 'socialnetworkapp-81ecc',
    storageBucket: 'socialnetworkapp-81ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvHhYIru-opBi6RU_vnp-ZER5JcRE2RWk',
    appId: '1:1060462154565:ios:bd7aba7346393bf372242c',
    messagingSenderId: '1060462154565',
    projectId: 'socialnetworkapp-81ecc',
    storageBucket: 'socialnetworkapp-81ecc.appspot.com',
    iosClientId: '1060462154565-5ssrk6h4715hn79vf0se1hf79q5bc5r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialnetworkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvHhYIru-opBi6RU_vnp-ZER5JcRE2RWk',
    appId: '1:1060462154565:ios:09b296a25811ba9e72242c',
    messagingSenderId: '1060462154565',
    projectId: 'socialnetworkapp-81ecc',
    storageBucket: 'socialnetworkapp-81ecc.appspot.com',
    iosClientId: '1060462154565-86n6dic47eut260ebfn4o0ncfm5vgtil.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialnetworkapp.RunnerTests',
  );
}
